name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing files and committing changes
      pull-requests: write  # Allow commenting on PRs and creating/updating PRs
      issues: write  # Allow commenting on issues
      id-token: write
      actions: read  # Allow reading workflow status
      checks: read  # Allow reading check status
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Allow Claude to run comprehensive bash commands for development
          allowed_tools: |
            Bash(*)
            Bash(npm:*)
            Bash(git:*)
            Bash(npm install)
            Bash(npm run *)
            Bash(npm run build)
            Bash(npm run dev)
            Bash(npm run test)
            Bash(git add)
            Bash(git commit)
            Bash(git push)
            Bash(git pull)
            Bash(git status)
            Bash(ls)
            Bash(pwd)
            Bash(cat)
            Bash(find)
            Bash(grep)
            Edit
            Write
            Read
            MultiEdit
            Glob
            LS
          
          # Custom instructions for Claude specific to Phoenix Technology Center
          custom_instructions: |
            This is the Phoenix Technology Center website built with Eleventy + Tailwind CSS.
            - Always run npm install and npm run build to test changes
            - Maintain the professional tech center branding and messaging
            - Use Lucide icons consistently (data-lucide="icon-name")
            - Follow the modern CSS patterns established in the codebase
            - Check CLAUDE.md for project-specific guidance
          
          # Environment variables for Claude
          claude_env: |
            NODE_ENV: development
            CI: true

